(function(){
  'use strict';
  const CONFIG=Object.freeze({
    appName:'Thalys',
    appVersion:'0.54.4',
    cacheBust:'0544',
    sessionSchema:'v1',
    storageSchemaVersion:4,
    syncProtocolVersion:7,
    features:Object.freeze({
      indexedDbPrimary:true,
      driveOnlyProgressPhotos:true,
      autoSyncOnReconnect:true,
      capabilityLayer:true,
      deviceMediaLayer:true,
      voiceDictation:true,
      notificationLayer:true,
      pushFoundation:true,
      backendBridge:true,
      pushClient:true,
      freeTierPolicy:true,
      backendFreeScaffold:true,
      googleServerAuthBridge:true,
      backendDeploymentGuard:true,
      finalArchitectureHardening:true
    }),
    costPolicy:Object.freeze({
      mode:'free-only',
      allowPaidServices:false,
      allowAutomaticUpgrade:false,
      aiFreeTierOnly:true,
      aiPaidFallback:false,
      progressPhotos:'google-drive-only',
      appData:'google-drive-plus-indexeddb',
      backendPreference:'cloudflare-workers-free'
    }),
    backend:Object.freeze({
      enabled:true,
      deploymentStage:'stable-free-backend',
      contractVersion:'1',
      autoActivate:false,
      provider:'cloudflare-workers-free',
      freeTierOnly:true,
      requiresBilling:false,
      baseUrl:'https://thalys.thalys-app.workers.dev',
      vapidPublicKey:'',
      healthPath:'/health',
      pushSubscribePath:'/push/subscriptions',
      pushUnsubscribePath:'/push/subscriptions/remove',
      pushConfigPath:'/push/config',
      pushTestPath:'/push/test',
      googleCodeFlowEnabled:true,
      googleClientId:'530515970912-7mlo4stsbcbcajrov07f911se4upv8t2.apps.googleusercontent.com',
      googleScopes:'https://www.googleapis.com/auth/drive https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email',
      googleCodeExchangePath:'/auth/google/code',
      googleRefreshPath:'/auth/google/refresh',
      googleStatusPath:'/auth/google/status',
      googleLogoutPath:'/auth/google/logout'
    })
  });
  window.ThalysConfig=CONFIG;
  window.THALYS_APP_VERSION=CONFIG.appVersion;
})();
