(function(){
  'use strict';
  const CONFIG=Object.freeze({
    appName:'Thalys',
    appVersion:'0.41.0',
    cacheBust:'0410',
    sessionSchema:'v1',
    storageSchemaVersion:4,
    syncProtocolVersion:7,
    features:Object.freeze({
      indexedDbPrimary:true,
      driveOnlyProgressPhotos:true,
      autoSyncOnReconnect:true,
      capabilityLayer:true,
      deviceMediaLayer:true,
      voiceDictation:true,
      notificationLayer:true,
      pushFoundation:true,
      backendBridge:true,
      pushClient:true
    }),
    backend:Object.freeze({
      enabled:false,
      provider:'none',
      baseUrl:'',
      vapidPublicKey:'',
      healthPath:'/health',
      pushSubscribePath:'/push/subscriptions',
      pushUnsubscribePath:'/push/subscriptions/remove',
      googleRefreshPath:'/auth/google/refresh'
    })
  });
  window.ThalysConfig=CONFIG;
  window.THALYS_APP_VERSION=CONFIG.appVersion;
})();
