(function(){
  'use strict';
  const CONFIG=Object.freeze({
    appName:'Thalys',
    appVersion:'0.42.0',
    cacheBust:'0420',
    sessionSchema:'v1',
    storageSchemaVersion:4,
    syncProtocolVersion:7,
    features:Object.freeze({
      indexedDbPrimary:true,
      driveOnlyProgressPhotos:true,
      autoSyncOnReconnect:true,
      capabilityLayer:true,
      deviceMediaLayer:true,
      voiceDictation:true,
      notificationLayer:true,
      pushFoundation:true,
      backendBridge:true,
      pushClient:true,
      freeTierPolicy:true,
      backendFreeScaffold:true
    }),
    costPolicy:Object.freeze({
      mode:'free-only',
      allowPaidServices:false,
      allowAutomaticUpgrade:false,
      aiFreeTierOnly:true,
      aiPaidFallback:false,
      progressPhotos:'google-drive-only',
      appData:'google-drive-plus-indexeddb',
      backendPreference:'cloudflare-workers-free'
    }),
    backend:Object.freeze({
      enabled:false,
      provider:'cloudflare-workers-free',
      freeTierOnly:true,
      requiresBilling:false,
      baseUrl:'',
      vapidPublicKey:'',
      healthPath:'/health',
      pushSubscribePath:'/push/subscriptions',
      pushUnsubscribePath:'/push/subscriptions/remove',
      googleRefreshPath:'/auth/google/refresh'
    })
  });
  window.ThalysConfig=CONFIG;
  window.THALYS_APP_VERSION=CONFIG.appVersion;
})();
